<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-05T12:30:05 IST" name="tutorialsninja" finished-at="2023-08-05T12:30:33 IST" duration-ms="27858">
    <groups>
    </groups>
    <test started-at="2023-08-05T12:30:05 IST" name="firsttestng" finished-at="2023-08-05T12:30:33 IST" duration-ms="27858">
      <class name="com.tutorialsninja.qa.testcases.register">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.testcases.register@7dfd3c81]" started-at="2023-08-05T12:30:05 IST" name="setup" finished-at="2023-08-05T12:30:11 IST" duration-ms="5546" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="registerwithvalidcredentials()[pri:0, instance:com.tutorialsninja.qa.testcases.register@7dfd3c81]" started-at="2023-08-05T12:30:11 IST" name="registerwithvalidcredentials" finished-at="2023-08-05T12:30:12 IST" duration-ms="1513" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerwithvalidcredentials -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.testcases.register@7dfd3c81]" started-at="2023-08-05T12:30:12 IST" name="teardown" finished-at="2023-08-05T12:30:13 IST" duration-ms="262" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.tutorialsninja.qa.testcases.register -->
      <class name="com.tutorialsninja.qa.testcases.search">
        <test-method is-config="true" signature="setup2()[pri:0, instance:com.tutorialsninja.qa.testcases.search@3b35a229]" started-at="2023-08-05T12:30:29 IST" name="setup2" finished-at="2023-08-05T12:30:32 IST" duration-ms="3456" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup2 -->
        <test-method signature="searchcontext()[pri:0, instance:com.tutorialsninja.qa.testcases.search@3b35a229]" started-at="2023-08-05T12:30:32 IST" name="searchcontext" finished-at="2023-08-05T12:30:33 IST" duration-ms="555" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchcontext -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.testcases.search@3b35a229]" started-at="2023-08-05T12:30:33 IST" name="teardown" finished-at="2023-08-05T12:30:33 IST" duration-ms="262" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.tutorialsninja.qa.testcases.search -->
      <class name="com.tutorialsninja.qa.testcases.Login">
        <test-method is-config="true" signature="mainmetod()[pri:0, instance:com.tutorialsninja.qa.testcases.Login@700fb871]" started-at="2023-08-05T12:30:14 IST" name="mainmetod" finished-at="2023-08-05T12:30:17 IST" duration-ms="3752" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mainmetod -->
        <test-method signature="loginwithvaildcredentials(java.lang.String,java.lang.String)[pri:1, instance:com.tutorialsninja.qa.testcases.Login@700fb871]" started-at="2023-08-05T12:30:17 IST" name="loginwithvaildcredentials" data-provider="suplytestdata" finished-at="2023-08-05T12:30:18 IST" duration-ms="948" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[sangetha@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1234]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.tutorialsninja.qa.testcases.Login.loginwithvaildcredentials(Login.java:67)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginwithvaildcredentials -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.testcases.Login@700fb871]" started-at="2023-08-05T12:30:18 IST" name="teardown" finished-at="2023-08-05T12:30:19 IST" duration-ms="245" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="mainmetod()[pri:0, instance:com.tutorialsninja.qa.testcases.Login@700fb871]" started-at="2023-08-05T12:30:19 IST" name="mainmetod" finished-at="2023-08-05T12:30:21 IST" duration-ms="2544" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mainmetod -->
        <test-method signature="loginwithvaildcredentials(java.lang.String,java.lang.String)[pri:1, instance:com.tutorialsninja.qa.testcases.Login@700fb871]" started-at="2023-08-05T12:30:21 IST" name="loginwithvaildcredentials" data-provider="suplytestdata" finished-at="2023-08-05T12:30:22 IST" duration-ms="1241" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[bharathdevadiga11@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[12345]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.tutorialsninja.qa.testcases.Login.loginwithvaildcredentials(Login.java:67)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginwithvaildcredentials -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.testcases.Login@700fb871]" started-at="2023-08-05T12:30:22 IST" name="teardown" finished-at="2023-08-05T12:30:23 IST" duration-ms="250" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="mainmetod()[pri:0, instance:com.tutorialsninja.qa.testcases.Login@700fb871]" started-at="2023-08-05T12:30:23 IST" name="mainmetod" finished-at="2023-08-05T12:30:28 IST" duration-ms="5316" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mainmetod -->
        <test-method signature="Loginwithinvalidcredentials()[pri:2, instance:com.tutorialsninja.qa.testcases.Login@700fb871]" started-at="2023-08-05T12:30:28 IST" name="Loginwithinvalidcredentials" finished-at="2023-08-05T12:30:29 IST" duration-ms="611" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Loginwithinvalidcredentials -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.testcases.Login@700fb871]" started-at="2023-08-05T12:30:29 IST" name="teardown" finished-at="2023-08-05T12:30:29 IST" duration-ms="240" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.tutorialsninja.qa.testcases.Login -->
    </test> <!-- firsttestng -->
  </suite> <!-- tutorialsninja -->
</testng-results>
